import Head from "next/head";

import Steps from "@/components/steps";
import Image from "next/image";
import Header from "@/components/ui/header";

export default function Home() {
	return (
		<>
			<Head>
				<title>Corsi</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={`bg-white flex flex-col h-screen justify-end`}>
				<Header />
				<Steps />
			</main>
		</>
	);
}
