import Head from "next/head";
import Steps from "@/components/steps";
import Header from "@/components/ui/header";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Courses() {
	return (
		<>
			<Head>
				<title>Corsi</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main
				className={`bg-white flex flex-col h-screen justify-end ${inter.className}`}
			>
				<Header />
				<Steps />
			</main>
		</>
	);
}
