import Head from "next/head";

import { Inter } from "next/font/google";
import Steps from "@/components/steps";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"], variable: "--inter-font" });

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main
				className={`bg-white flex flex-col h-screen justify-end ${inter.variable}`}
			>
				<nav className=" bg-slate-500">
					<Image
						alt="logo"
						src="/assets/school/6.png"
						width={100}
						height={40}
					/>
				</nav>
				<Steps />
			</main>
		</>
	);
}
